### ISSUE TITLE
attention mechanism on the top layer

### ISSUE THREAD

**Issue by Jiakui** [xueyouluo/my_seq2seq#4]
From this repository,   https://github.com/JayParks/tf-seq2seq/blob/master/seq2seq_model.py  , I noticed a note saying: 
        # Note: We implement Attention mechanism only on the top decoder layer

Correspondingly, the code looks like: 

        self.decoder_cell_list[-1] = attention_wrapper.AttentionWrapper(
            cell=self.decoder_cell_list[-1],
            attention_mechanism=self.attention_mechanism,
            attention_layer_size=self.hidden_units,
            cell_input_fn=attn_decoder_input_fn,
            initial_cell_state=encoder_last_state[-1],
            alignment_history=False,
            name='Attention_Wrapper')

Why do you add attention to the zeroth decoder layer ? I think the top layer version sounds more reasonable. Thanks!

**Comment by xueyouluo** [comment]
@Jiakui good question! 
Yes, usually we put the attention mechanism on the top layer, the problem is which layer is top layer? 0 or -1? The reason I choose the first layer is:
- from the code of [MulitRNN](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell_impl.py ), I found that the code iterator the rnn cells from left to right, which means the leftmost cell is the top layer. So I choose 0 as the first layer, and -1 as the last layer
- correct me if I misunderstood the code :)

Another interesting founding is, when you look at the attention code of [nmt](https://github.com/tensorflow/nmt/blob/master/nmt/attention_model.py), you will found that it has wrapped all the cells:
```python
    cell = tf.contrib.seq2seq.AttentionWrapper(
        cell,
        attention_mechanism,
        attention_layer_size=num_units,
        alignment_history=alignment_history,
        name="attention")
```
The best way is to read the source code of seq2seq, which is what I will do next.

**Comment by Jiakui** [comment]
I will try it in my own project, whether it should be the 0th layer, -1th layer, or all the layers. 

Thanks!

**Comment by xueyouluo** [comment]
Haha, 不管黑猫白猫，能work才是好猫。

**Comment by Jiakui** [comment]
if you don't mind, can we chat on 微信 ? you can contact me at 微信号 sherchy 。

Thanks!
